Show history of all archived projects, not just those that were rejected.
MIT-LCP/physionet-build pull request #2023
Opened 2023-06-16 17:21 UTC by tompollard

## Motivation for the change

There are different reasons for projects to be "archived". One reason is that users decide to close a project themselves. Another reason is that a project is rejected after submission.

As far as I'm aware, the only archived projects that are viewable in the system are ones that were rejected. These can be viewed in the console at: https://physionet.org/console/rejected-submissions/

Currently, there are a large number of archived submissions which are invisible to administrators. We should fix this, to make sure all archived projects can be found.

## What is the change

This pull request follows https://github.com/MIT-LCP/physionet-build/pull/2018. We now display all archived projects in the console, not just those that were rejected.

## Future work

In a later pull request, I intend to make additional improvements, for example displaying the archiving reason in the submission history and in the project list at: https://physionet.org/console/rejected-submissions/

https://github.com/MIT-LCP/physionet-build/issues/612 is a related issue. Once this pull request is (I hope) merged, then I will follow up with changes that allow more metadata to be retained.

2023-06-26 20:40 UTC, alistairewj requested changes
One quick change, otherwise LGTM

2023-06-26 20:40 UTC, alistairewj commented on physionet-django/console/templates/console/archived_submissions.html
Line 5, 14, and 27 look like they need an update to "Archived"

2023-06-26 20:46 UTC, tompollard commented on physionet-django/console/templates/console/archived_submissions.html
Good catch, thanks. I think this page will need a bit work later (preferably in a new PR), so that it displays more meaningful information in the list (e.g. reason for archiving).

2023-06-27 14:03 UTC, alistairewj approved these changes

2023-06-27 14:03 UTC, merged